---
services:
  coala-bot:
    image: "debelzak/coala-bot:latest"
    container_name: "coala-bot"
    environment:
      - DEVELOPMENT=${DEVELOPMENT}
      - SILENT=${SILENT}
      - BOT_TOKEN=${BOT_TOKEN}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - ./database:/usr/app/database